# -*- coding: utf-8 -*-
"""Mod2-Assignment .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-_vv_KaYfrDLs6VuLsT_7f2Y4-Dhwco5
"""

def inputSame(a, b): 
 
   if (a ^ b):  
 
       print ("Not Same") 
 
   else: 
 
       print ("Same") 
 
inputSame(40, 30)

def inputSame(a, b): 
 
   if (a ^ b):  
 
       print ("Not Same") 
 
   else: 
 
       print ("Same") 
 
inputSame(30, 30)