# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IWA8lLsbMD179tTUclktP28B6pKT7rp7
"""

a= int(input('enter frist number'))
b=int(input('enter secound number'))
c=int(input('enter third number'))
i=max(a,b,c)
print('max number is',i)

