# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LXhbUx57O--i8OYNwNSBj33pjI0SSrWx
"""

a= int(input('enter the first number'))
b=int(input('enter the second number'))
sum=a+b;
if(sum>5):
    print("Sum is greater than 5" )
elif(sum<5):
    print("Sum is less than 5" )
else:
    print("Sum is equals to 5" )