# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15pRpyW8GxrrhJ4UgnkBt6tMRPBVx2ofV
"""

a= int(input('enter sutdent marks between 1 to 100'))  
if(a>34):
    print('passed the exam')
else:
    print('failed the exam')