# -*- coding: utf-8 -*-
"""Mod2-Q5Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157EXPIEJI0wLxtCB1sln3QCUa-LVZdUM
"""

def maximum(a, b, c): 
 
    if (a >= b) and (a >= c): 
 
        largest = a 
 
    elif (b >= a) and (b >= c): 
         largest = b 
 
    else: 
        largest = c 
 
    return largest 
 
a = 65
 
b = 80
 
c = 100
 
print(maximum(a, b, c))