# -*- coding: utf-8 -*-
"""Mod2-Assignment .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14BR0bOBX3BPtfZQBtlyMo7MaAiotngmQ
"""

print ("first number") 
x = input()
print ("second number") 
y= input()
print ("third number") 
z= input()
all = x == y and y== z and z== x
print ("All are equal:",all) 
any = x== y or y == z or z == x
print ("Any of two are equal:",any)

print ("first number") 
x = input()
print ("second number") 
y= input()
print ("third number") 
z= input()
all = x == y and y== z and z== x
print ("All are equal:",all) 
any = x== y or y == z or z == x
print ("Any of two are equal:",any)